# Generated by Django 4.0.4 on 2022-05-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fololwing',
            new_name='folowing',
        ),
    ]
