# Generated by Django 4.0.4 on 2022-05-22 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_post_edited_post_is_visible'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
